### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by belazr** [SteamKaibz/DE_AdvancedOptionsModPublic#1]
To continue our conversation from bruhmoment21/UniversalHookX#18 a couple of questions:

Did you have any more user reporting about the AMD fix?
Did people report performance issues with the fix?
Have you experienced the performance issues yourself?
Can you describe them in more detail? Frame rate drops? Microstutters? How much performance is lost? When do they occur?
Are there only issues with present from compute enabled in the settings menu?

**Comment by SteamKaibz** [comment]
So far 3 users who could not use the mod before, reported that they can use it because of the changes you made.
No confirmation however that the performance issue is still occuring with the fix, i sent a msg to the user who had reported it and i should have a confirmation soon (hopefully). I know he uses a 9900k intel cpu and that he doesn't use present for compute.
I had experienced these performance issues myself before BUT they were (and are still) caused by the fact that the mod is generating a custom grenade icon (which is NOT generated with imgui but by the game UI itself using a hook) and this is exactly why i decided to use imgui to generate hud elements so that i would not have to use this grenade icon using a game hook, so the perf loss would be close to null. 
However when this user reported me that he had performance issue using the custom Hud (Imgui) i realised that the performance issue might still be happening. 
The perf issues i experimented at the time were very weird, as it's not a constant framerate drop but only in certain situations, when a lot of things are happening in game. I would say about 5 to 10 % performance lost overall. 
I suppose at this point, if this user can confirm the issue is only happening when he's using the "dedicated grenade keys" feature, then it would mean that it has nothing to do with vulkan/imgui. 
I will post here as soon as i hear from him.
Side note, i credited you i think in the DE mod menu and in the nexus page, unless you don't want me to do so.

**Comment by belazr** [comment]
Ok, I did some further testing.

I could now see a significant performance drop with the mod running. But only in CPU bound scenarios, which makes sense and could be what you describe with: "_...as it's not a constant frame rate drop but only in certain situations, when a lot of things are happening in game_"
DEs advanced performance metrics and the fact that my CPU is definitely under-powered for my GPU helped a lot here :)

I modified the mod so I could load and unload it during runtime, tested on a Ryzen R5 3600 and a 7900 XT and came up with the following numbers:

Without the mod the CPU frame time was about **3.5 ms** in the area when you first go outside (has a huge demon to the left, no idea what its called, probably 5 min into the game).
With the mod the CPU frame time went to about **5 ms**. Since I was CPU bound the whole time that results in a frame drop from around 285 fps to around 200 fps.

The mod using as much CPU power as 40% of the game seemed way to much for me, so I benchmarked the mod step by step.
I benched the Vulkan hook to almost exactly **1.5** ms on average, so that is definitely where the performance gets lost.
After more benching, I found that almost all of the 1.5 ms are spent in the `idHudManager::getIdHud_Element` calls in `KaibzHudManager::getData`:

```
idHUD_LowWarning* idHUD_LowWarningPtr = (idHUD_LowWarning*)idHudManager::getIdHud_Element(HudElementName::LowWarning);
idHUD_AbilityIndicators* idHUD_AbilityIndicatorsPtr = (idHUD_AbilityIndicators*)idHudManager::getIdHud_Element(HudElementName::AbilityIndicators);
idHUD_ExtraLives* idHUD_ExtraLivesPtr = (idHUD_ExtraLives*)idHudManager::getIdHud_Element(HudElementName::ExtraLives);
idHUD_WeaponInfo* idHud_WeaponInfoPtr = (idHUD_WeaponInfo*)idHudManager::getIdHud_Element(HudElementName::WeaponInfo);
idHUD_HealthInfo* idHUD_HealthInfoPtr = (idHUD_HealthInfo*)idHudManager::getIdHud_Element(HudElementName::HealthInfo);
idHUD_BloodPunch* idHUD_BloodPunchPtr = (idHUD_BloodPunch*)idHudManager::getIdHud_Element(HudElementName::BloodPunch);
```

I am pretty confident that what it comes down to in the end are the multiple calls to `MemHelper::isBadReadPtr`. The `VirtualQuery` call inside of it is pretty expensive to do over and over in a hook.

Since I am not familiar with the engine and the SDK, I am not sure if those checks are necessary in a production environment.
I tested with

```
bool MemHelper::isBadReadPtr(void* ptr)
{
#ifdef _DEBUG
	MEMORY_BASIC_INFORMATION mbi = { 0 };
	if (::VirtualQuery(ptr, &mbi, sizeof(mbi)))
	{
		DWORD mask = (PAGE_READONLY | PAGE_READWRITE | PAGE_WRITECOPY | PAGE_EXECUTE_READ | PAGE_EXECUTE_READWRITE | PAGE_EXECUTE_WRITECOPY);
		bool b = !(mbi.Protect & mask);
		// check the page is not a guard page
		if (mbi.Protect & (PAGE_GUARD | PAGE_NOACCESS)) b = true;

		return b;
	}
	return true;
#else
	return false;
#endif
}
```

and the total time of the hook went down to **0.12ms** on average for a Release build and the performance impact of the mod was almost negligible.
This **could** work in general (I couldn't see anything suspicious) though **I would strongly advise against using it, since it might crash the game on some occasions.**
Are you familiar enough with the engine and the SDK to judge if these checks are necessary?

So to be on the safe side, I implemented a caching mechanism for the `idHUDElement` pointers inside of the `idHudManager`.
This got the total time of the hook to **0.28 ms**, which is still a lot better coming from **1.5ms**.
I'm still doing some testing with it but everything looks fine so far.

I would rule out https://github.com/bruhmoment21/UniversalHookX as the culprit for now :)

I will open a pull request so you can test the changes yourself. I am happy for any feedback you can give!
Exiting to the menu and then reloading a game was a case I almost overlooked at first but it also seems fine.

As for the "dedicated grenade keys":
I couldn't find the feature, maybe I can look into that as well if you point me in the right direction :)

**Comment by belazr** [comment]
Oh and thanks for crediting me :)
